/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
RouteRecordInfo
} from 'vue-router';

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'about': RouteRecordInfo<'about', '/apropos', Record<never, never>, Record<never, never>>,
    'map': RouteRecordInfo<'map', '/carte', Record<never, never>, Record<never, never>>,
    'legal': RouteRecordInfo<'legal', '/mentions-legales', Record<never, never>, Record<never, never>>,
    'searchCom': RouteRecordInfo<'searchCom', '/recherche/commune/:codeCommune/:codePostal/:nomCommune/:typeRecherche/:codeTriCentre/:includesOnline', Record<never, never>, Record<never, never>>,
    '/TalkAboutIt': RouteRecordInfo<'/TalkAboutIt', '/TalkAboutIt', Record<never, never>, Record<never, never>>,
  }
}
